image: docker:19.03.11
services:
  - docker:19.03.11-dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/kingify/web:dashboard .
    - docker push registry.gitlab.com/kingify/web:dashboard
  only:
    - dashboard/deploy

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apk --update add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -m 700 -p /root/.ssh
    - ssh -o StrictHostKeyChecking=no thanh@tvtprod.com "sudo docker run -d --restart on-failure registry.gitlab.com/kingify/web:dashboard"
  only:
    - dashboard/deploy
